import type { SiteLocale } from "./locales";

export type RegionalHubKey = "planner" | "questions" | "guides" | "resources" | "embed" | "methodology";

type HubCard = {
  title: string;
  description: string;
};

export type RegionalHubContent = {
  label: string;
  eyebrow: string;
  title: string;
  description: string;
  introTitle: string;
  intro: string;
  cards: HubCard[];
  action: string;
  noteTitle: string;
  note: string;
  home: string;
  section: string;
};

export const localizedHubPaths: Record<SiteLocale, Record<RegionalHubKey, string>> = {
  en: {
    planner: "/freight-planner", questions: "/questions", guides: "/guides", resources: "/resources", embed: "/embed", methodology: "/methodology",
  },
  nl: {
    planner: "/nl/vrachtplanner", questions: "/nl/vragen", guides: "/nl/gidsen", resources: "/nl/bronnen", embed: "/nl/inbedden", methodology: "/nl/methode",
  },
  de: {
    planner: "/de/frachtplaner", questions: "/de/fragen", guides: "/de/ratgeber", resources: "/de/quellen", embed: "/de/einbetten", methodology: "/de/methode",
  },
  fr: {
    planner: "/fr/planificateur-fret", questions: "/fr/questions", guides: "/fr/guides", resources: "/fr/ressources", embed: "/fr/integrer", methodology: "/fr/methode",
  },
  ja: {
    planner: "/ja/freight-planner", questions: "/ja/questions", guides: "/ja/guides", resources: "/ja/resources", embed: "/ja/embed", methodology: "/ja/methodology",
  },
  zh: {
    planner: "/zh/freight-planner", questions: "/zh/questions", guides: "/zh/guides", resources: "/zh/resources", embed: "/zh/embed", methodology: "/zh/methodology",
  },
};

const nl: Record<RegionalHubKey, RegionalHubContent> = {
  planner: { label: "Vrachtplanner", eyebrow: "Drie controles voor uw zending", title: "Controleer ruimte, gewicht en offertebasis voordat u boekt.", description: "Werk met de afmetingen en limieten die u al heeft. De planner helpt u de juiste controle in de juiste volgorde te doen.", introTitle: "Begin met de gegevens op uw paklijst", intro: "Meet de buitenmaten van de afgewerkte lading, noteer het gewogen gewicht en controleer welke pallet en voertuig worden gebruikt.", cards: [{ title: "1. Laadruimte", description: "Bereken laadmeters voor pallets en vergelijk die met de beschikbare voertuiglengte." }, { title: "2. Gewicht", description: "Vergelijk werkelijk gewicht met de limiet van voertuig, pallet of vervoerder." }, { title: "3. Offerte", description: "Bewaar de regel, munt en datum naast uw uitkomst voordat u prijzen vergelijkt." }], action: "Laadmeter berekenen", noteTitle: "Voor een offerte is één berekening niet genoeg", note: "Bevestig altijd de actuele vervoerdersregel, materieellimiet en afgesproken tarieven.", home: "Start", section: "Vrachtplanner" },
  questions: { label: "Vragen", eyebrow: "Korte antwoorden voor dagelijkse verzendingen", title: "Vind de vraag achter de berekening.", description: "Gebruik deze startpunten wanneer u weet wat er mis kan gaan, maar niet welke formule u nodig heeft.", introTitle: "Veelvoorkomende controles", intro: "De antwoorden zijn bedoeld als praktische voorbereiding op een offerte, laadplan of gesprek met een vervoerder.", cards: [{ title: "Past deze pallet in de vrachtwagen?", description: "Gebruik de palletvoetafdruk en het aantal pallets om de benodigde laadlengte te schatten." }, { title: "Welke palletmaat moet ik gebruiken?", description: "Vergelijk EPAL-, blok- en industriële palletten met de maat van uw dozen." }, { title: "Welke maat moet ik doorgeven?", description: "Gebruik altijd de buitenmaat van de verpakte en verzendklare lading." }], action: "Open de laadmetercalculator", noteTitle: "Het resultaat is een planning", note: "Een chauffeur, vervoerder of magazijn kan aanvullende veiligheids- en laadregels toepassen.", home: "Start", section: "Vragen" },
  guides: { label: "Gidsen", eyebrow: "Van meten tot boeken", title: "Werk met een vaste werkwijze, niet met een gok.", description: "Deze gids vat de controles samen die bij pallet- en wegtransport vaak een verschil maken.", introTitle: "Praktische volgorde", intro: "Meet eerst, kies daarna de pallet en controleer pas dan voertuigruimte en offertevoorwaarden.", cards: [{ title: "Palletvoetafdruk", description: "Waarom lengte en breedte vaak belangrijker zijn dan het aantal dozen alleen." }, { title: "Laadmeters", description: "Hoe de ingenomen vloeroppervlakte naar een vergelijkbare voertuiglengte wordt omgerekend." }, { title: "Hoogte en gewicht", description: "Waarom een resultaat nog niet bevestigt dat stapelen of zekeren is toegestaan." }], action: "Bereken laadmeters", noteTitle: "Gebruik dezelfde eenheden", note: "Controleer of uw invoer in millimeters, centimeters of meters is voordat u een uitkomst deelt.", home: "Start", section: "Gidsen" },
  resources: { label: "Bronnen", eyebrow: "Controleerbare referenties", title: "Handige tabellen voor de controle vóór verzending.", description: "Gebruik de bronnen als aanvulling op uw eigen tarief, palletafspraak en veiligheidsinstructie.", introTitle: "Wat u hier vindt", intro: "De bestanden bevatten gebruikte regels, bronverwijzingen en een revisiedatum zodat een uitkomst controleerbaar blijft.", cards: [{ title: "Palletafmetingen", description: "Veelgebruikte EPAL-, GMA- en industriële voetafdrukken voor een eerste laadcontrole." }, { title: "DIM- en volumegegevens", description: "Referenties voor verpakkings- en vrachtberekeningen; raadpleeg altijd uw eigen contractregel." }, { title: "Offertecontrole", description: "Een korte lijst voor maat, gewicht, minimumtarief, toeslagen en datum." }], action: "Laadmeter controleren", noteTitle: "Controleer de bron bij elke wijziging", note: "Tarieven en vervoerdersvoorwaarden kunnen per route, contract en datum verschillen.", home: "Start", section: "Bronnen" },
  embed: { label: "Inbedden", eyebrow: "Voor artikelen en interne kennisbanken", title: "Voeg een bruikbare vrachtcontrole toe aan uw eigen pagina.", description: "Laat lezers de berekening in hun browser uitvoeren en verwijs voor de aannames terug naar ShipMathLab.", introTitle: "Eenvoudig en transparant", intro: "Gebruik een duidelijke titel, behoud de bronvermelding en controleer na publiceren of de calculator binnen uw layout past.", cards: [{ title: "Kies een onderwerp", description: "Gebruik laadmeters voor voertuigruimte en pallets; kies een andere tool voor pakket- of LCL-vragen." }, { title: "Plaats de iframe", description: "De calculator wordt op ShipMathLab gehost en vraagt geen account of API-sleutel." }, { title: "Noem de beperking", description: "Vermeld dat de uitkomst een planning is en geen bevestigde vervoerdersofferte." }], action: "Open de insluitbare calculator", noteTitle: "Behoud de verwijzing", note: "Een link naar de formule en bron helpt lezers de uitkomst verantwoord te gebruiken.", home: "Start", section: "Inbedden" },
  methodology: { label: "Methode", eyebrow: "Hoe de berekening wordt opgebouwd", title: "Volg de regel terug naar de invoer.", description: "Een bruikbare vrachtberekening combineert rekenwerk, een operationele regel en een limiet die de calculator niet zelf kan goedkeuren.", introTitle: "De controle in drie lagen", intro: "De formule verwerkt uw gegevens; de vervoerders- of palletregel bepaalt de aannames; de echte lading moet daarna nog worden gecontroleerd.", cards: [{ title: "Bronnen", description: "Waar mogelijk gebruiken we vervoerders-, norm- en palletreferenties met een controledatum." }, { title: "Aannames", description: "Materiële invoer en beperkingen worden naast het resultaat getoond, niet erachter verstopt." }, { title: "Operationele controle", description: "Stabiliteit, zekering, voertuig en contract blijven de verantwoordelijkheid van de uitvoerende partij." }], action: "Start een laadmeterberekening", noteTitle: "Laatste controle", note: "Bevestig kritieke waarden met de vervoerder, leverancier of magazijnverantwoordelijke.", home: "Start", section: "Methode" },
};

const de: Record<RegionalHubKey, RegionalHubContent> = {
  planner: { label: "Frachtplaner", eyebrow: "Drei Prüfungen für Ihre Sendung", title: "Prüfen Sie Platz, Gewicht und Angebotsbasis vor der Buchung.", description: "Arbeiten Sie mit den Maßen und Grenzen, die bereits auf Ihrer Packliste stehen.", introTitle: "Mit den Versanddaten beginnen", intro: "Messen Sie die Außenmaße der fertigen Ladung, notieren Sie das gewogene Gewicht und prüfen Sie Palette und Fahrzeug.", cards: [{ title: "1. Laderaum", description: "Berechnen Sie Lademeter für Paletten und vergleichen Sie sie mit der nutzbaren Fahrzeuglänge." }, { title: "2. Gewicht", description: "Vergleichen Sie das tatsächliche Gewicht mit den Grenzen von Fahrzeug, Palette und Frachtführer." }, { title: "3. Angebot", description: "Notieren Sie Regel, Währung und Datum neben dem Ergebnis, bevor Sie Preise vergleichen." }], action: "Lademeter berechnen", noteTitle: "Eine Berechnung ersetzt kein Angebot", note: "Bestätigen Sie stets die aktuelle Frachtführerregel, die Betriebsmittelgrenze und die vereinbarten Tarife.", home: "Start", section: "Frachtplaner" },
  questions: { label: "Fragen", eyebrow: "Direkte Antworten für den Versandalltag", title: "Finden Sie die Frage hinter der Berechnung.", description: "Diese Einstiegspunkte helfen, wenn Sie das Risiko kennen, aber die benötigte Formel noch nicht.", introTitle: "Häufige Prüfungen", intro: "Die Antworten bereiten auf Angebot, Ladeplan oder Gespräch mit dem Frachtführer vor.", cards: [{ title: "Passt diese Palette ins Fahrzeug?", description: "Nutzen Sie Grundfläche und Palettenanzahl, um die benötigte Ladefläche zu schätzen." }, { title: "Welche Palette ist passend?", description: "Vergleichen Sie EPAL-, Industrie- und andere Paletten mit Ihren Kartonmaßen." }, { title: "Welche Maße sind maßgeblich?", description: "Übermitteln Sie immer die Außenmaße der fertig verpackten, versandbereiten Ware." }], action: "Lademeter-Rechner öffnen", noteTitle: "Ergebnis nur zur Planung", note: "Fahrer, Frachtführer oder Lager können weitere Lade- und Sicherheitsregeln anwenden.", home: "Start", section: "Fragen" },
  guides: { label: "Ratgeber", eyebrow: "Vom Messen bis zur Buchung", title: "Arbeiten Sie nach einer festen Reihenfolge.", description: "Dieser Ratgeber fasst die Prüfungen zusammen, die bei Paletten- und Straßentransport häufig entscheidend sind.", introTitle: "Praktische Reihenfolge", intro: "Zuerst messen, dann Palette wählen, danach Fahrzeugraum und Angebotsbedingungen prüfen.", cards: [{ title: "Paletten-Grundfläche", description: "Warum Länge und Breite oft wichtiger sind als die Kartonzahl allein." }, { title: "Lademeter", description: "Wie belegte Bodenfläche in vergleichbare Fahrzeuglänge umgerechnet wird." }, { title: "Höhe und Gewicht", description: "Warum ein Ergebnis nicht automatisch Stapelung oder Sicherung freigibt." }], action: "Lademeter berechnen", noteTitle: "Einheiten konsistent halten", note: "Prüfen Sie vor dem Teilen des Ergebnisses, ob alle Maße in Millimeter, Zentimeter oder Metern vorliegen.", home: "Start", section: "Ratgeber" },
  resources: { label: "Quellen", eyebrow: "Nachprüfbare Referenzen", title: "Tabellen für die Kontrolle vor dem Versand.", description: "Nutzen Sie die Quellen zusammen mit Ihrem Tarif, Ihrer Palettenvereinbarung und Ihren Sicherheitsvorgaben.", introTitle: "Inhalt der Referenzen", intro: "Die Dateien enthalten verwendete Regeln, Quellen und ein Prüfdatenfeld für nachvollziehbare Ergebnisse.", cards: [{ title: "Palettenmaße", description: "Gängige EPAL-, GMA- und Industrie-Grundflächen für eine erste Ladeprüfung." }, { title: "DIM und Volumen", description: "Referenzen für Verpackungs- und Frachtberechnungen; maßgeblich bleibt Ihr Vertrag." }, { title: "Angebotsprüfung", description: "Eine kurze Liste für Maße, Gewicht, Mindesttarif, Zuschläge und Datum." }], action: "Lademeter prüfen", noteTitle: "Quelle bei Änderungen prüfen", note: "Tarife und Frachtführerbedingungen können sich nach Route, Vertrag und Datum unterscheiden.", home: "Start", section: "Quellen" },
  embed: { label: "Einbetten", eyebrow: "Für Artikel und Wissensdatenbanken", title: "Fügen Sie eine nutzbare Frachtprüfung in Ihre Seite ein.", description: "Leser rechnen im Browser; für Annahmen und Quellen führt ein Link zurück zu ShipMathLab.", introTitle: "Einfach und nachvollziehbar", intro: "Verwenden Sie einen eindeutigen Titel, behalten Sie die Quellenangabe bei und prüfen Sie nach Veröffentlichung das Layout.", cards: [{ title: "Thema wählen", description: "Nutzen Sie Lademeter für Paletten und Fahrzeugraum; wählen Sie für andere Fälle das passende Werkzeug." }, { title: "Iframe einfügen", description: "Der Rechner läuft bei ShipMathLab und benötigt weder Konto noch API-Schlüssel." }, { title: "Grenze benennen", description: "Machen Sie deutlich, dass es sich um eine Planung und nicht um ein bestätigtes Angebot handelt." }], action: "Einbettbaren Rechner öffnen", noteTitle: "Verweis beibehalten", note: "Ein Link zu Formel und Quelle hilft Lesern, das Ergebnis richtig einzuordnen.", home: "Start", section: "Einbetten" },
  methodology: { label: "Methode", eyebrow: "So entsteht die Berechnung", title: "Die Regel bis zur Eingabe zurückverfolgen.", description: "Eine brauchbare Frachtberechnung verbindet Rechenweg, operative Regel und eine Grenze, die kein Rechner selbst freigeben kann.", introTitle: "Prüfung in drei Ebenen", intro: "Die Formel verarbeitet Ihre Daten; die Regel definiert die Annahmen; die reale Ladung wird anschließend separat geprüft.", cards: [{ title: "Quellen", description: "Wo möglich nutzen wir Frachtführer-, Norm- und Palettenreferenzen mit Prüfdaten." }, { title: "Annahmen", description: "Wesentliche Eingaben und Grenzen stehen neben dem Ergebnis, nicht im Kleingedruckten." }, { title: "Operative Freigabe", description: "Stabilität, Sicherung, Fahrzeug und Vertrag bleiben bei der ausführenden Partei." }], action: "Lademeter berechnen", noteTitle: "Letzte Prüfung", note: "Bestätigen Sie kritische Werte mit Frachtführer, Lieferant oder Lagerverantwortung.", home: "Start", section: "Methode" },
};

const fr: Record<RegionalHubKey, RegionalHubContent> = {
  planner: { label: "Planificateur fret", eyebrow: "Trois vérifications avant l'expédition", title: "Vérifiez l'espace, le poids et la base du devis avant de réserver.", description: "Partez des dimensions et limites déjà présentes sur votre liste de colisage.", introTitle: "Commencez par les données d'expédition", intro: "Mesurez les dimensions extérieures de la charge finie, notez le poids mesuré et confirmez palette et véhicule.", cards: [{ title: "1. Espace de chargement", description: "Calculez les mètres de plancher pour les palettes et comparez-les à la longueur utile du véhicule." }, { title: "2. Poids", description: "Comparez le poids réel aux limites du véhicule, de la palette et du transporteur." }, { title: "3. Devis", description: "Notez la règle, la devise et la date avec le résultat avant de comparer les prix." }], action: "Calculer les mètres de plancher", noteTitle: "Un calcul ne remplace pas un devis", note: "Confirmez toujours la règle actuelle du transporteur, les limites du matériel et les tarifs convenus.", home: "Accueil", section: "Planificateur fret" },
  questions: { label: "Questions", eyebrow: "Réponses directes pour l'expédition", title: "Trouvez la question derrière le calcul.", description: "Ces points de départ sont utiles lorsque vous connaissez le risque, sans savoir encore quelle formule employer.", introTitle: "Vérifications fréquentes", intro: "Les réponses préparent un devis, un plan de chargement ou un échange avec le transporteur.", cards: [{ title: "Cette palette tient-elle dans le camion ?", description: "Utilisez l'empreinte au sol et le nombre de palettes pour estimer la longueur nécessaire." }, { title: "Quelle palette choisir ?", description: "Comparez les formats EPAL, industriels et autres à vos cartons." }, { title: "Quelles dimensions transmettre ?", description: "Utilisez toujours les dimensions extérieures de la marchandise emballée et prête à expédier." }], action: "Ouvrir le calculateur", noteTitle: "Résultat de planification", note: "Le conducteur, le transporteur ou l'entrepôt peuvent appliquer d'autres règles de sécurité et de chargement.", home: "Accueil", section: "Questions" },
  guides: { label: "Guides", eyebrow: "De la mesure à la réservation", title: "Suivez une méthode plutôt que de deviner.", description: "Ce guide rassemble les contrôles qui changent souvent une décision de palette ou de transport routier.", introTitle: "Ordre pratique", intro: "Mesurez d'abord, choisissez la palette, puis vérifiez l'espace véhicule et les conditions du devis.", cards: [{ title: "Empreinte de palette", description: "Pourquoi longueur et largeur comptent souvent davantage que le seul nombre de cartons." }, { title: "Mètres de plancher", description: "Comment la surface au sol occupée devient une longueur comparable dans un véhicule." }, { title: "Hauteur et poids", description: "Pourquoi un résultat n'autorise pas automatiquement l'empilage ou l'arrimage." }], action: "Calculer maintenant", noteTitle: "Gardez les mêmes unités", note: "Avant de partager un résultat, vérifiez si toutes les dimensions sont en millimètres, centimètres ou mètres.", home: "Accueil", section: "Guides" },
  resources: { label: "Ressources", eyebrow: "Références vérifiables", title: "Des tableaux utiles avant l'expédition.", description: "Utilisez ces ressources avec votre tarif, votre accord palette et vos consignes de sécurité.", introTitle: "Contenu des ressources", intro: "Les fichiers indiquent les règles utilisées, les sources et une date de vérification pour rendre le calcul contrôlable.", cards: [{ title: "Dimensions de palettes", description: "Empreintes EPAL, GMA et industrielles courantes pour une première vérification." }, { title: "DIM et volume", description: "Références de colis et fret ; votre règle contractuelle reste déterminante." }, { title: "Contrôle de devis", description: "Une liste courte pour dimensions, poids, minimum, suppléments et date." }], action: "Vérifier les mètres de plancher", noteTitle: "Vérifiez la source à chaque changement", note: "Les tarifs et conditions peuvent changer selon l'itinéraire, le contrat et la date.", home: "Accueil", section: "Ressources" },
  embed: { label: "Intégrer", eyebrow: "Pour articles et bases de connaissances", title: "Ajoutez un contrôle fret utile à votre propre page.", description: "Les lecteurs calculent dans leur navigateur et retrouvent les hypothèses et sources sur ShipMathLab.", introTitle: "Simple et transparent", intro: "Utilisez un titre clair, gardez l'attribution et vérifiez l'affichage après publication.", cards: [{ title: "Choisir le sujet", description: "Les mètres de plancher conviennent aux palettes et à l'espace véhicule ; choisissez l'outil adapté aux autres cas." }, { title: "Insérer l'iframe", description: "Le calculateur est hébergé par ShipMathLab et ne demande ni compte ni clé API." }, { title: "Indiquer la limite", description: "Précisez que le résultat est une estimation de planification, pas un devis confirmé." }], action: "Ouvrir le calculateur intégrable", noteTitle: "Conservez le lien", note: "Le lien vers la formule et la source aide vos lecteurs à utiliser le résultat correctement.", home: "Accueil", section: "Intégrer" },
  methodology: { label: "Méthode", eyebrow: "Comment le calcul est construit", title: "Remontez de la règle jusqu'aux données saisies.", description: "Un calcul fret utile combine l'arithmétique, une règle opérationnelle et une limite que le calculateur ne peut pas approuver seul.", introTitle: "Trois niveaux de vérification", intro: "La formule traite vos données ; la règle fixe les hypothèses ; le chargement réel doit ensuite être contrôlé séparément.", cards: [{ title: "Sources", description: "Nous privilégions les références transporteurs, normes et palettes avec une date de revue." }, { title: "Hypothèses", description: "Les entrées et limites importantes sont visibles à côté du résultat." }, { title: "Validation opérationnelle", description: "Stabilité, arrimage, véhicule et contrat restent à la charge de l'opérateur." }], action: "Calculer les mètres de plancher", noteTitle: "Dernière vérification", note: "Confirmez les valeurs critiques avec le transporteur, le fournisseur ou le responsable d'entrepôt.", home: "Accueil", section: "Méthode" },
};

const ja: Record<RegionalHubKey, RegionalHubContent> = {
  planner: { label: "輸送プランナー", eyebrow: "出荷前の3つの確認", title: "予約前に、スペース・重量・見積条件を確認します。", description: "すでにある梱包明細の寸法と制限値から始められます。", introTitle: "出荷データから始める", intro: "完成した貨物の外寸、実測重量、使用するパレットと車両を確認してください。", cards: [{ title: "1. 荷台スペース", description: "パレットの必要荷台長を計算し、車両の有効長と比較します。" }, { title: "2. 重量", description: "実重量を、車両・パレット・運送会社の制限と比較します。" }, { title: "3. 見積", description: "価格を比べる前に、適用ルール・通貨・日付を結果と一緒に記録します。" }], action: "荷台長を計算する", noteTitle: "計算だけで見積は確定しません", note: "最新の運送会社規定、車両制限、契約運賃を必ず確認してください。", home: "ホーム", section: "輸送プランナー" },
  questions: { label: "質問", eyebrow: "日々の出荷のための簡潔な答え", title: "計算の前に、確認したいことを整理します。", description: "リスクは分かっていても必要な計算式が不明なときの出発点です。", introTitle: "よくある確認", intro: "見積、積載計画、運送会社との確認に進むための実務的な案内です。", cards: [{ title: "このパレットは車両に載る？", description: "パレットの床面積と台数から、必要な荷台長を見積もります。" }, { title: "どのパレットを使う？", description: "JPR T11などのパレット寸法と段ボール外寸を比較します。" }, { title: "どの寸法を伝える？", description: "必ず梱包済みで出荷可能な状態の外寸を使います。" }], action: "荷台長計算を開く", noteTitle: "結果は計画用です", note: "運転手、運送会社、倉庫は追加の積載・安全ルールを適用する場合があります。", home: "ホーム", section: "質問" },
  guides: { label: "ガイド", eyebrow: "計測から予約まで", title: "推測ではなく、順序立てて確認します。", description: "パレット輸送や陸上輸送で判断を左右しやすい確認項目をまとめています。", introTitle: "実務上の順序", intro: "最初に測定し、次にパレットを選び、その後で車両スペースと見積条件を確認します。", cards: [{ title: "パレットの床面積", description: "段ボール数だけでなく、長さと幅が重要になる理由。" }, { title: "荷台長", description: "占有する床面積を車両内の比較可能な長さへ換算する考え方。" }, { title: "高さと重量", description: "計算結果が積み重ねや固縛の許可を意味しない理由。" }], action: "荷台長を計算する", noteTitle: "単位を統一する", note: "結果を共有する前に、入力がmm・cm・mのどれかを確認してください。", home: "ホーム", section: "ガイド" },
  resources: { label: "資料", eyebrow: "確認できる参照情報", title: "出荷前の確認に使える表。", description: "自社の運賃、パレット仕様、安全指示とあわせて利用してください。", introTitle: "資料に含まれる内容", intro: "使用したルール、出典、確認日を示し、計算結果を追跡できるようにします。", cards: [{ title: "パレット寸法", description: "初期確認に使えるJPR、EPAL、GMA、工業用パレットの代表的な床面積。" }, { title: "DIMと容積", description: "梱包・貨物計算の参照値。契約上のルールが最優先です。" }, { title: "見積の確認", description: "寸法、重量、最低料金、追加料金、日付を確認する短い一覧。" }], action: "荷台長を確認する", noteTitle: "変更時は出典を再確認", note: "運賃と運送会社の条件は、経路・契約・日付により変わります。", home: "ホーム", section: "資料" },
  embed: { label: "埋め込み", eyebrow: "記事や社内ナレッジ向け", title: "自分のページに役立つ輸送チェックを追加。", description: "読者はブラウザ上で計算し、前提と出典はShipMathLabで確認できます。", introTitle: "シンプルで透明性のある利用", intro: "分かりやすいタイトルと出典表示を残し、公開後にレイアウトを確認してください。", cards: [{ title: "用途を選ぶ", description: "荷台長はパレットと車両スペース向けです。別の用途には適したツールを選んでください。" }, { title: "iframeを追加", description: "計算器はShipMathLabで動作し、アカウントやAPIキーは不要です。" }, { title: "制限を示す", description: "結果は計画用であり、確定した運送見積ではないことを明記します。" }], action: "埋め込み計算器を開く", noteTitle: "参照リンクを残す", note: "数式と出典へのリンクが、読者の適切な判断を助けます。", home: "ホーム", section: "埋め込み" },
  methodology: { label: "計算方法", eyebrow: "計算の組み立て方", title: "ルールを入力値までたどります。", description: "役立つ輸送計算には、計算式、運用ルール、計算器だけでは承認できない現場の制限があります。", introTitle: "3層の確認", intro: "数式がデータを処理し、ルールが前提を決め、実際の貨物は別途確認します。", cards: [{ title: "出典", description: "可能な限り、確認日を付けた運送会社・規格・パレットの情報を使用します。" }, { title: "前提", description: "重要な入力と制限は、結果のそばに表示します。" }, { title: "現場での確認", description: "安定性、固縛、車両、契約の確認は実務担当者の責任です。" }], action: "荷台長を計算する", noteTitle: "最終確認", note: "重要な値は運送会社、仕入先、倉庫責任者に確認してください。", home: "ホーム", section: "計算方法" },
};

const zh: Record<RegionalHubKey, RegionalHubContent> = {
  planner: { label: "货运规划", eyebrow: "发货前的三项检查", title: "订舱前先核对空间、重量和报价依据。", description: "直接使用装箱单上已经有的尺寸和限制条件。", introTitle: "从发货数据开始", intro: "测量包装完成后货物的外尺寸，记录称重重量，并确认使用的托盘和车型。", cards: [{ title: "1. 车厢空间", description: "计算托盘所占的车厢长度，再与车辆的可用长度比较。" }, { title: "2. 重量", description: "把实际重量与车辆、托盘和承运商的限制进行比较。" }, { title: "3. 报价", description: "比较价格前，把适用规则、币种和日期与结果一起记录下来。" }], action: "计算车厢长度", noteTitle: "一次计算不能代替正式报价", note: "请确认最新的承运商规则、车辆限制和合同运价。", home: "首页", section: "货运规划" },
  questions: { label: "问答", eyebrow: "日常发货的直接答案", title: "先找到计算背后的实际问题。", description: "当你知道风险在哪里、但不知道该用哪个公式时，可以从这里开始。", introTitle: "常见检查", intro: "这些内容用于帮助你准备报价、装载计划或与承运商沟通。", cards: [{ title: "这个托盘能装进货车吗？", description: "根据托盘占地面积和数量，估算需要多少车厢长度。" }, { title: "该用什么托盘？", description: "将国标、欧标或工业托盘的尺寸与纸箱外尺寸进行比较。" }, { title: "要给出哪组尺寸？", description: "始终使用完成包装、可直接发货货物的外尺寸。" }], action: "打开车厢长度计算器", noteTitle: "结果用于规划", note: "司机、承运商或仓库可能还有额外的装载和安全要求。", home: "首页", section: "问答" },
  guides: { label: "指南", eyebrow: "从测量到订舱", title: "按顺序检查，而不是凭感觉。", description: "这里总结了托盘和公路货运中常常会改变决策的关键检查项。", introTitle: "实用顺序", intro: "先测量，再选托盘，最后检查车辆空间和报价条件。", cards: [{ title: "托盘占地面积", description: "为什么长度和宽度往往比纸箱数量本身更重要。" }, { title: "车厢长度", description: "如何把实际占用的地板面积换算为可比较的车辆长度。" }, { title: "高度与重量", description: "为什么计算结果不代表已经获准堆叠或绑扎。" }], action: "立即计算", noteTitle: "统一单位", note: "分享结果前，请确认输入使用的是毫米、厘米还是米。", home: "首页", section: "指南" },
  resources: { label: "资料", eyebrow: "可核验的参考资料", title: "发货前可以使用的参考表。", description: "请将这些资料与自己的运价、托盘约定和安全要求一起使用。", introTitle: "资料包含什么", intro: "文件会标出使用规则、来源和审核日期，让计算结果能够被复查。", cards: [{ title: "托盘尺寸", description: "用于初步装载检查的常见国标、EPAL、GMA和工业托盘占地面积。" }, { title: "DIM与体积", description: "包装和货运计算的参考信息；最终以你的合同规则为准。" }, { title: "报价检查", description: "检查尺寸、重量、最低收费、附加费和日期的简明清单。" }], action: "检查车厢长度", noteTitle: "变化时重新核验来源", note: "运价和承运商条件会因路线、合同和日期而不同。", home: "首页", section: "资料" },
  embed: { label: "嵌入", eyebrow: "面向文章和内部知识库", title: "把实用的货运检查放进你自己的页面。", description: "读者可在浏览器中完成计算，并回到ShipMathLab查看假设和来源。", introTitle: "简单且透明", intro: "使用清晰的标题，保留来源说明，并在发布后检查页面布局。", cards: [{ title: "选择用途", description: "车厢长度适合托盘和车辆空间；其他问题请选用相应工具。" }, { title: "加入 iframe", description: "计算器由ShipMathLab托管，不需要账户或API密钥。" }, { title: "说明限制", description: "请明确结果仅用于规划，不是承运商确认的报价。" }], action: "打开可嵌入计算器", noteTitle: "保留引用链接", note: "指向公式和来源的链接能帮助读者正确使用结果。", home: "首页", section: "嵌入" },
  methodology: { label: "计算方法", eyebrow: "计算如何建立", title: "从规则追溯到输入数据。", description: "有用的货运计算包括算术、决定输入的运营规则，以及计算器无法自行批准的现场限制。", introTitle: "三层检查", intro: "公式处理你的数据，规则决定前提，实际货物仍需单独检查。", cards: [{ title: "来源", description: "在条件允许时，使用带审核日期的承运商、标准和托盘资料。" }, { title: "假设", description: "重要输入和限制会在结果旁显示，而不是藏在说明里。" }, { title: "现场确认", description: "稳定性、绑扎、车辆和合同仍需由实际执行方确认。" }], action: "计算车厢长度", noteTitle: "最后检查", note: "关键数值请向承运商、供应商或仓库负责人确认。", home: "首页", section: "计算方法" },
};

export const regionalHubContent: Partial<Record<SiteLocale, Record<RegionalHubKey, RegionalHubContent>>> = { nl, de, fr, ja, zh };

export function getRegionalHub(locale: SiteLocale, section: string) {
  if (locale === "en") return null;
  const key = (Object.keys(localizedHubPaths[locale]) as RegionalHubKey[]).find(
    (candidate) => localizedHubPaths[locale][candidate].endsWith(`/${section}`),
  );
  if (!key) return null;
  return regionalHubContent[locale]?.[key] ? { key, content: regionalHubContent[locale][key] } : null;
}

export const allLocalizedHubPaths = (Object.keys(localizedHubPaths) as SiteLocale[])
  .filter((locale) => locale !== "en")
  .flatMap((locale) => Object.values(localizedHubPaths[locale]));
