export type ToolDefinition = {
  slug: string;
  title: string;
  shortTitle: string;
  category: string;
  tag: string;
  description: string;
  intro: string;
  formula: string;
  assumption: string;
  reviewed?: string;
  sources?: Array<{ label: string; url: string }>;
  workedExample?: {
    title: string;
    steps: string[];
    result: string;
  };
  commonMistakes?: string[];
};

export const tools: ToolDefinition[] = [
  {
    slug: "dimensional-weight-calculator",
    title: "Dimensional Weight Calculator with FedEx, UPS, DHL & USPS Divisors",
    shortTitle: "Dimensional Weight",
    category: "Parcel",
    tag: "kg · lb",
    description: "Enter a packed box size and scale weight; the calculator chooses a planning rule and shows the likely billed weight.",
    intro: "No divisor knowledge required: choose the closest shipping setup, enter the sealed parcel size and scale weight, and compare actual with dimensional weight automatically.",
    formula: "Dimensional weight = (length × width × height) ÷ divisor",
    assumption: "Carriers use different divisors by service, account, and destination. Confirm the divisor and rounding rules on your rate card before quoting.",
    reviewed: "August 11, 2026",
    sources: [
      { label: "FedEx dimensional weight guidance", url: "https://www.fedex.com/en-us/shipping/packaging/what-is-dimensional-weight.html" },
      { label: "UPS dimensional weight and rate-type divisors", url: "https://developer.ups.com/us/en/support/shipping-support/shipping-dimensions-weight" },
      { label: "DHL volumetric weight guidance", url: "https://www.dhl.com/discover/en-gb/ship-with-dhl/products-and-services/weight-and-dimensions" },
      { label: "USPS dimensional weight example", url: "https://pe.usps.com/QSG_Archive/NHTML/QSG_Archive_20250119/Q201e.htm" },
    ],
    workedExample: {
      title: "50 × 40 × 30 cm parcel at a 5,000 divisor",
      steps: [
        "Volume: 50 × 40 × 30 = 60,000 cm³.",
        "Dimensional weight: 60,000 ÷ 5,000 = 12 kg.",
        "Compare with 7 kg actual weight, then apply the selected billing increment per parcel.",
      ],
      result: "The planning chargeable basis is 12 kg per parcel before any service-specific measurement rule or surcharge.",
    },
    commonMistakes: [
      "Mixing centimetre/kilogram and inch/pound divisors.",
      "Using product dimensions instead of the finished outside package.",
      "Rounding only the shipment total when the carrier bills each parcel.",
      "Treating a public preset as the rule in a negotiated contract.",
    ],
  },
  {
    slug: "cbm-calculator",
    title: "CBM Calculator — Cubic Metres for Freight & Shipping",
    shortTitle: "CBM & Volume",
    category: "Freight",
    tag: "m³ · ft³",
    description: "Calculate shipping volume in cubic metres, cubic feet, and litres for cartons, crates, pallets, or a full freight shipment.",
    intro: "Enter the packed outside dimensions and quantity—no unit conversion required. The calculator returns total CBM, cubic feet, litres, and volume per piece for a freight quote.",
    formula: "Total volume = length × width × height × quantity",
    assumption: "This is external carton volume. It does not include pallet dimensions, protective overhang, or irregular packing space.",
    reviewed: "August 14, 2026",
    sources: [
      { label: "Maersk guidance for calculating LCL CBM", url: "https://www.maersk.com/fr-fr/support/faqs/how-can-calculate-my-lcl-cbm-volumes" },
    ],
    workedExample: {
      title: "24 cartons at 60 × 40 × 35 cm",
      steps: [
        "Convert centimetres to metres: 0.60 × 0.40 × 0.35.",
        "Volume per carton: 0.084 m³.",
        "Shipment volume: 0.084 × 24 = 2.016 m³.",
      ],
      result: "Enter 2.016 CBM on the freight request before any carrier rounding, palletisation, or chargeable-weight rule.",
    },
    commonMistakes: [
      "Using product dimensions instead of the finished carton, crate, or pallet envelope.",
      "Mixing centimetres, metres, inches, and feet on the same cargo line.",
      "Adding loose-carton CBM and palletised CBM for the same freight.",
      "Treating physical CBM as chargeable volume without checking weight, minimums, and tariff rules.",
    ],
  },
  {
    slug: "carton-fit-calculator",
    title: "Carton Fit Calculator",
    shortTitle: "Carton Fit",
    category: "Packing",
    tag: "6 rotations",
    description: "Find the best right-angle orientation for fitting identical items inside a master carton.",
    intro: "Test all six axis-aligned rotations of an item and find the arrangement that fits the highest whole-number quantity inside a carton.",
    formula: "Fit count = floor(box L ÷ item L) × floor(box W ÷ item W) × floor(box H ÷ item H)",
    assumption: "The estimate assumes rectangular items, straight rows, no nesting, no deformation, and no clearance or protective material.",
  },
  {
    slug: "pallet-load-calculator",
    title: "Pallet Loading Calculator — Cartons per Layer, Height & Weight",
    shortTitle: "Pallet Load",
    category: "Warehouse",
    tag: "layers · weight",
    description: "Choose a familiar pallet and enter one packed carton; the calculator handles rotation, layers, height and weight limits.",
    intro: "No pallet formula required: choose Euro, industrial, GMA or half-Euro, enter one carton’s outside size and weight, and get a complete example loading plan with editable limits.",
    formula: "Cartons = min(cartons per layer × layers, floor(max load weight ÷ carton weight))",
    assumption: "This planning estimate assumes no overhang and identical cartons. It does not assess compression strength, stability, local rules, or safe working load.",
    reviewed: "August 11, 2026",
    sources: [
      { label: "EPAL Euro pallet specifications", url: "https://www.epal-pallets.org/eu-en/load-carriers/epal-euro-pallet" },
      { label: "ISO 6780 pallet dimensions overview", url: "https://www.iso.org/standard/30524.html" },
    ],
    workedExample: {
      title: "1,200 × 1,000 mm pallet with 400 × 300 × 250 mm cartons",
      steps: [
        "The best straight-row orientation fits 3 × 3 cartons, or 9 per layer.",
        "A 165 cm total-height limit less a 15 cm pallet base leaves 150 cm: 6 full layers.",
        "Geometry allows 54 cartons; a 1,000 kg cargo limit at 20 kg per carton allows only 50.",
      ],
      result: "The weight limit controls at 50 cartons, subject to pallet rating, compression and stability approval.",
    },
    commonMistakes: [
      "Forgetting that a total-height limit includes the pallet base and load restraints.",
      "Counting cartons from area percentages instead of whole rows.",
      "Using pallet capacity as proof that the bottom cartons can carry the stack.",
      "Optimising count without documenting orientation, wrap and overhang rules.",
    ],
  },
  {
    slug: "container-loading-calculator",
    title: "Container Loading Calculator",
    shortTitle: "Container Loading",
    category: "Freight",
    tag: "20ft · 40ft · HC",
    description: "Estimate axis-aligned carton capacity for 20ft, 40ft, and 40ft high-cube containers.",
    intro: "Compare six carton rotations against representative internal container dimensions to estimate a simple, uniform loading plan.",
    formula: "Capacity = max of six floor(container dimension ÷ carton dimension) combinations",
    assumption: "Container interiors vary by manufacturer. This simplified estimate excludes door clearance, weight distribution, pallets, mixed orientations, and loading constraints.",
  },
  {
    slug: "package-girth-calculator",
    title: "Package Length + Girth Calculator",
    shortTitle: "Length + Girth",
    category: "Parcel",
    tag: "carrier limits",
    description: "Calculate package length plus girth and compare it with a limit from your carrier.",
    intro: "Enter the three outside dimensions of a parcel. The longest side is treated as length and the other two sides form the girth.",
    formula: "Length + girth = longest side + 2 × (second side + shortest side)",
    assumption: "Carrier size limits and measurement rounding vary. Enter the limit shown in the applicable service guide or contract.",
  },
  {
    slug: "shipping-unit-converter",
    title: "Shipping Unit Converter",
    shortTitle: "Unit Converter",
    category: "Utility",
    tag: "length · mass · volume",
    description: "Convert the length, mass, and volume units used across international shipping documents.",
    intro: "Convert common metric and imperial measurements without leaving your packing workflow. Results update as you type.",
    formula: "Converted value = input value × source factor ÷ destination factor",
    assumption: "Conversions use standard mathematical factors. Displayed values are rounded for readability while calculations retain full precision.",
  },
  {
    slug: "corrugated-box-cost-calculator",
    title: "Corrugated Box Cost Calculator",
    shortTitle: "Box Cost Estimate",
    category: "Packaging",
    tag: "RSC estimate",
    description: "Estimate RSC corrugated blank area, material usage, waste, and a batch material cost.",
    intro: "Create a quick material estimate for a regular slotted container using box dimensions, manufacturer joint, waste allowance, quantity, and sheet price.",
    formula: "Blank area ≈ [2(L + W) + joint] × (H + W)",
    assumption: "This is a material-planning estimate for a basic RSC layout, not a production quote. Scores, trim, flute allowance, setup, printing, and labour are excluded.",
  },
  {
    slug: "shipping-cost-estimator",
    title: "Shipping Cost Estimator",
    shortTitle: "Shipping Cost",
    category: "Parcel",
    tag: "rate + surcharge",
    description: "Estimate a parcel charge from billable weight, per-kilo rate, fuel surcharge, and handling.",
    intro: "Combine actual weight and dimensional weight with your own contracted rate, surcharge, handling fee, and parcel quantity.",
    formula: "Total = [(chargeable weight × rate) × (1 + surcharge)] + handling",
    assumption: "The result excludes taxes, duties, remote-area fees, minimum charges, weight steps, and other carrier-specific adjustments.",
  },
  {
    slug: "ecommerce-margin-calculator",
    title: "Ecommerce Margin Calculator",
    shortTitle: "Ecommerce Margin",
    category: "Commerce",
    tag: "profit · break-even",
    description: "See profit, margin, fees, return on cost, and break-even price for an ecommerce order.",
    intro: "Combine product, shipping, packaging, marketplace, payment, advertising, and other order costs to see the true contribution margin.",
    formula: "Profit = selling price − fixed order costs − percentage fees",
    assumption: "The estimate is before income tax and overhead unless you enter those costs. Returns, discounts, and currency movement are not modelled.",
  },
  {
    slug: "freight-density-calculator",
    title: "Freight Density Calculator",
    shortTitle: "Freight Density",
    category: "Freight",
    tag: "kg/m³ · lb/ft³",
    description: "Calculate shipment density from outside dimensions, quantity, and total gross weight.",
    intro: "Convert a shipment's total cube and gross weight into kilograms per cubic metre and pounds per cubic foot for quoting and load planning.",
    formula: "Density = total gross weight ÷ total outside volume",
    assumption: "This tool calculates physical density only. It does not assign an NMFC freight class or replace a carrier's classification rules.",
  },
  {
    slug: "air-freight-chargeable-weight-calculator",
    title: "Air Freight Chargeable Weight Calculator",
    shortTitle: "Air Chargeable Weight",
    category: "Air freight",
    tag: "gross vs volume",
    description: "Compare gross and volumetric weight for a multi-piece air freight shipment.",
    intro: "Estimate the chargeable weight of identical air cargo pieces using outside dimensions, gross weight, quantity, and a selectable volume divisor.",
    formula: "Chargeable weight = max(gross weight, L × W × H × pieces ÷ divisor)",
    assumption: "Airlines and forwarders may use different divisors, minimums, rounding, or piece-level rules. Use the divisor and method shown in your quote.",
  },
  {
    slug: "lcl-chargeable-volume-calculator",
    title: "LCL Chargeable Volume Calculator — W/M & CBM",
    shortTitle: "LCL W/M Charge",
    category: "Ocean freight",
    tag: "CBM · metric tonne",
    description: "Enter cargo size, quantity and packed weight; the calculator converts everything to CBM, tonnes and chargeable W/M automatically.",
    intro: "No W/M knowledge or freight quote required: enter each carton, crate or pallet line and get the chargeable CBM/tonne basis. Add ocean and local prices only when you have them.",
    formula: "W/M units = max(total CBM, gross metric tonnes); total = W/M units × rate + fixed fees",
    assumption: "Tariffs can use minimums, density rules, local charges, and currencies that differ from this simple W/M model. Follow the forwarder's quote.",
    reviewed: "August 11, 2026",
    sources: [
      { label: "Maersk LCL weight and measure terms", url: "https://terms.maersk.com/LCL" },
      { label: "Maersk shipping glossary — W/M", url: "https://www.maersk.com/de-de/support/glossaries/shipping-terms" },
    ],
    workedExample: {
      title: "Ten cartons at 100 × 80 × 80 cm and 42 kg each",
      steps: [
        "Volume: 1.00 × 0.80 × 0.80 × 10 = 6.4 CBM.",
        "Gross weight: 42 × 10 = 420 kg, or 0.42 metric tonnes.",
        "Compare 6.4 measure units with 0.42 weight units, then apply the quote minimum automatically.",
      ],
      result: "Volume controls at 6.4 W/M units in this common model; fixed origin, destination and document fees remain separate.",
    },
    commonMistakes: [
      "Adding carton cube and palletised cube for the same cargo.",
      "Comparing kilograms directly with CBM instead of converting to metric tonnes under the quoted rule.",
      "Applying one minimum to the whole invoice when different fee lines have different minimums.",
      "Ranking quotes by ocean rate while omitting destination and document charges.",
    ],
  },
  {
    slug: "load-meter-calculator",
    title: "Load Meter Calculator",
    shortTitle: "Load Metres",
    category: "Road freight",
    tag: "LDM · floor space",
    description: "Convert shipment floor area into load metres for a standard-width trailer estimate.",
    intro: "Estimate how much trailer length a set of rectangular pallets or crates occupies, with an optional number of safely stackable layers.",
    formula: "Load metres = length × width × quantity ÷ trailer width ÷ stackable layers",
    assumption: "This assumes efficient rectangular floor placement and even stackability. Confirm trailer width, loading layout, axle limits, and stack safety.",
  },
  {
    slug: "landed-cost-calculator",
    title: "Landed Cost Calculator — Duty, Tax, Freight & Unit Cost",
    shortTitle: "Landed Cost",
    category: "Commerce",
    tag: "duty · tax · freight",
    description: "Estimate total landed cost and landed cost per unit from goods, freight, insurance, customs duty, import tax, and clearance fees.",
    intro: "Enter one purchase order and the calculator builds the customs-value basis, duty, import tax, all-in landed total, and unit cost. Every rate remains editable for the destination and product.",
    formula: "Landed total = goods + freight + insurance + duty + import tax + other fees",
    assumption: "The tax base and customs value vary by jurisdiction and product. This model uses editable percentages and is not customs or tax advice.",
    reviewed: "August 14, 2026",
    sources: [
      { label: "U.S. Customs — determining customs value", url: "https://www.cbp.gov/trade/rulings/informed-compliance-publications/customs-value" },
      { label: "WTO customs valuation overview", url: "https://www.wto.org/english/tratop_e/cusval_e/cusval_info_e.htm" },
    ],
    workedExample: {
      title: "500 units at $18 with freight, duty, and import tax",
      steps: [
        "Goods value: 500 × $18 = $9,000; add $1,850 freight and $120 insurance for the editable customs-value basis.",
        "At 6.5%, illustrative duty is $713.05.",
        "At 10% on customs value plus duty, illustrative import tax is $1,168.31; then add $340 in other fees.",
      ],
      result: "The illustrative landed total is $13,191.36, or $26.38 per unit. Replace every rate and tax base with the destination's current rule.",
    },
    commonMistakes: [
      "Applying a duty rate without confirming the product classification and origin.",
      "Using purchase price alone when the jurisdiction includes freight or insurance in customs value.",
      "Omitting brokerage, inspection, port, bank, and destination charges.",
      "Comparing suppliers on unit price instead of landed cost per usable unit.",
    ],
  },
  {
    slug: "reorder-point-calculator",
    title: "Reorder Point Calculator",
    shortTitle: "Reorder Point",
    category: "Inventory",
    tag: "demand · lead time",
    description: "Estimate the stock level that should trigger a replenishment order.",
    intro: "Combine average daily demand, replenishment lead time, and safety stock to create a simple reorder trigger for one SKU.",
    formula: "Reorder point = average daily demand × lead time + safety stock",
    assumption: "This basic model assumes the averages you enter remain useful. Seasonality, supplier variability, minimum orders, and open purchase orders need separate review.",
  },
  {
    slug: "eoq-calculator",
    title: "Economic Order Quantity Calculator",
    shortTitle: "EOQ",
    category: "Inventory",
    tag: "order vs holding cost",
    description: "Balance annual ordering and holding costs with the classic EOQ model.",
    intro: "Estimate an economic replenishment quantity from annual demand, cost per order, and annual holding cost per unit.",
    formula: "EOQ = √(2 × annual demand × order cost ÷ annual holding cost per unit)",
    assumption: "The classic EOQ model assumes steady demand, stable costs, immediate replenishment, and no stockouts or quantity discounts.",
  },
  {
    slug: "warehouse-storage-cost-calculator",
    title: "Warehouse Storage Cost Calculator",
    shortTitle: "Storage Cost",
    category: "Warehouse",
    tag: "pallet · handling",
    description: "Estimate storage, inbound, outbound, and administration costs for a palletised shipment.",
    intro: "Combine pallet count, storage duration, monthly pallet rate, handling charges, and account fees into a simple warehouse cost estimate.",
    formula: "Total = pallets × months × storage rate + pallets × handling fees + administration",
    assumption: "This excludes minimum monthly bills, pick-and-pack, long-term surcharges, insurance, taxes, and non-standard handling unless entered in administration.",
  },
  {
    slug: "pallet-stack-height-calculator",
    title: "Pallet Stack Height Calculator",
    shortTitle: "Pallet Stack Height",
    category: "Warehouse",
    tag: "layers · clearance",
    description: "Calculate finished pallet height, cartons per layer, total cartons, and remaining height clearance.",
    intro: "Plan a column-stacked pallet from pallet footprint, base height, carton dimensions, layer count, and a transport height limit.",
    formula: "Finished height = pallet base height + carton height × layers",
    assumption: "The footprint estimate tests two carton orientations but not interlocking layouts. Check overhang, stability, compression, and equipment clearance.",
  },
  {
    slug: "packaging-waste-calculator",
    title: "Packaging Waste Calculator",
    shortTitle: "Packaging Waste",
    category: "Packaging",
    tag: "yield · material loss",
    description: "Measure material loss, usable yield, and waste cost for a packaging production run.",
    intro: "Compare purchased packaging material with good-output usage and optional recoverable scrap to see waste rate, net loss, and cost impact.",
    formula: "Net waste = purchased material − good-output material − recoverable scrap",
    assumption: "Use one consistent unit such as kilograms, sheets, or metres. This is a mass or quantity balance, not a lifecycle assessment.",
  },
];

export function getTool(slug: string) {
  return tools.find((tool) => tool.slug === slug);
}
