import type { Metadata } from "next";
import Image from "next/image";
import { SiteFooter, SiteHeader } from "../components/SiteChrome";
import { product, resourcePartners } from "../lib/monetization";

export const metadata: Metadata = {
  title: "Freight & Packaging Resources",
  description: "The FreightKit operations workbook and carefully selected logistics resources.",
  alternates: { canonical: "/resources" },
};

export default function ResourcesPage() {
  return <main><SiteHeader/><section className="shell collection-hero resource-hero"><p className="eyebrow">Resources</p><h1>Move from one answer<br/>to a repeatable workflow.</h1><p>The calculators handle one decision at a time. The workbook connects recurring quotes, landed costs, pallet plans, and product margins.</p></section><section className="product-band" id="spreadsheet-pack"><div className="shell product-grid"><div className="product-preview"><Image src="/workbook-preview.png" alt="Preview of the FreightKit Operations Workbook dashboard" width={1776} height={744} unoptimized/></div><div className="product-copy"><p className="eyebrow eyebrow-light">Downloadable spreadsheet pack</p><h2>{product.name}</h2><p className="product-price">${product.price} <span>one-time</span></p><p>A polished Excel workbook for small importers, ecommerce operators, and freight coordinators who need reusable working files—not another account.</p><ul><li>SKU and shipment master data</li><li>Batch dimensional-weight checks</li><li>Freight quote comparison</li><li>Carton and pallet planning</li><li>Landed cost and margin models</li><li>Dashboard with linked key outputs</li></ul>{product.checkoutUrl?<a className="button button-acid" href={product.checkoutUrl} rel="noopener noreferrer" target="_blank">Buy the workbook — ${product.price} ↗</a>:<div className="store-pending"><strong>Workbook complete · checkout not connected</strong><p>This private review build does not collect payment. Connect an approved merchant account with the product URL setting before launch.</p></div>}<p className="micro-copy">Editable .xlsx file · formula-driven · no macros · instant delivery after store connection</p></div></div></section><section className="shell partner-section"><div className="section-heading"><div><p className="eyebrow">Optional partner resources</p><h2>Relevant next steps,<br/>not random banners.</h2></div><p>Partner links only appear after an approved affiliate account and disclosure are configured. No paid links are active in this review build.</p></div><div className="partner-grid">{resourcePartners.map((partner)=><article className="partner-card" key={partner.name}><span>Editorial category</span><h3>{partner.name}</h3><p>{partner.description}</p>{partner.url?<a href={partner.url} target="_blank" rel="sponsored noopener noreferrer">View the recommended option ↗</a>:<strong>Link awaiting approval</strong>}</article>)}</div><p className="affiliate-note"><strong>Disclosure:</strong> if approved partner links are added, FreightKit may receive a commission from qualifying purchases without changing the price you pay. Recommendations must remain based on fit and usefulness.</p></section><SiteFooter/></main>;
}
