import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter, SiteHeader } from "../components/SiteChrome";

export const metadata: Metadata = { title: "About & Maintainer", description: "Why ShipMathLab exists, who maintains it, and how corrections are handled.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  return <main><SiteHeader/><article className="shell legal-page"><p className="updated">About ShipMathLab</p><h1>Useful answers, visible working.</h1><p>ShipMathLab is an independently maintained project from the Saigetsu233 GitHub account. It is a focused collection of free calculators for people who quote, pack, store, and ship physical products.</p><h2>What we optimise for</h2><p>Each tool starts with a practical decision, uses a transparent formula, links to its source trail, and states the assumptions that can change the answer. Inputs stay in your browser; an account is not required.</p><h2>How content is maintained</h2><p>Priority formulas are checked against carrier, standards-body, pallet-pool, or freight-provider material. A rule review date appears on the tool and material changes enter the public <Link href="/changelog">version log</Link>. The open formula implementations live on <a href="https://github.com/Saigetsu233/freightkit-calculators" target="_blank" rel="noopener noreferrer">GitHub</a>.</p><h2>What ShipMathLab is not</h2><p>These tools are planning aids. They do not replace a current carrier quotation, supplier drawing, structural assessment, customs advice, or safe-loading review. Equipment and contract rules vary, so verify critical numbers before committing money or cargo.</p><h2>Corrections</h2><p>Open a GitHub issue with the tool URL, the disputed formula or source, the expected result, and a primary reference. Reproducible corrections take priority over feature requests.</p></article><SiteFooter/></main>;
}
