import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "../components/SiteChrome";

export const metadata: Metadata = { title: "Version & Source Review Log", description: "ShipMathLab formula, source-review, and product release notes.", alternates: { canonical: "/changelog" } };

const changes = [
  { date: "2026-09-05", label: "September 5, 2026 · v1.7", title: "First browser-language regional calculator", items: ["Added a first-party Dutch load-meter calculator instead of relying on browser translation.", "Dutch browser languages now open the Dutch calculator from the homepage or English load-meter tool, while a visible language control preserves user choice.", "Added Dutch number formatting, metric inputs, EPAL 1 and EPAL 2 presets, an editable 2.40 m planning width, and English/Dutch hreflang links.", "Added EPAL and EU vehicle-dimension references; operational inputs remain editable because real carrier equipment can differ."] },
  { date: "2026-08-16", label: "August 16, 2026 · v1.6", title: "Carrier-rated dimensions and complete pallet counts", items: ["Dimensional-weight comparisons now apply carrier-specific dimension rounding before calculating each row.", "Added the USPS one-cubic-foot applicability check and the July 2026 divisor and rounding rule.", "Expanded pallet loading from one-pallet capacity to full shipment planning, including pallets required and the final partial pallet.", "Added concise tool search descriptions and meaningful route-level sitemap dates."] },
  { date: "2026-08-11", label: "August 11, 2026 · v1.4", title: "No freight knowledge required to start", items: ["Added the same plain-language input promise to all 20 calculators and moved calculator inputs closer to the first viewport.", "Reworked dimensional weight around a closest-match shipping setup, sealed parcel measurements, and scale weight instead of requiring a divisor choice.", "Reworked pallet loading around a pallet preset and one packed carton, with example transport limits clearly labelled and advanced dimensions optional.", "Made LCL W/M calculation independent from quote pricing: visitors can enter cargo facts first and add freight charges only if available.", "Added calculator-visible and input-started events so usability can be measured separately from completed calculations."] },
  { date: "2026-08-06", label: "August 6, 2026 · v1.3", title: "Reference assets and measurable distribution", items: ["Added DIM-divisor, pallet-dimension, and LCL quote-audit downloads.", "Added formula flow diagrams, print actions, copy-result events, embed-source analytics, and maintained-source records.", "Reviewed FedEx, UPS, DHL, USPS, EPAL, ISO, and Maersk reference links for the three priority tools."] },
  { date: "2026-08-05", label: "August 5, 2026 · v1.2", title: "Priority tool clusters", items: ["Expanded dimensional weight, pallet load, and LCL W/M with worked examples, error checks, and four distinct guides each.", "Published three no-key iframe calculators and the open formula repository."] },
  { date: "2026-08-03", label: "August 3, 2026 · v1.0", title: "Public launch", items: ["Released the original freight, packaging, inventory, warehouse, and ecommerce calculator collection."] },
];

export default function ChangelogPage() {
  return <main><SiteHeader/><div className="shell legal-page"><p className="updated">Version log</p><h1>What changed, and why.</h1><div className="change-list">{changes.map((change) => <article key={`${change.label}-${change.title}`}><time dateTime={change.date}>{change.label}</time><h2>{change.title}</h2><ul>{change.items.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></div><SiteFooter/></main>;
}
