import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter, SiteHeader } from "../components/SiteChrome";

export const metadata: Metadata = { title: "Calculation & Content Method", description: "How ShipMathLab selects sources, tests formulas, reviews rules, and separates planning estimates from operational approvals.", alternates: { canonical: "/methodology" } };

export default function MethodologyPage() {
  return <main><SiteHeader/><div className="shell legal-page method-ledger"><p className="updated">Calculation and content method</p><h1>Trace the answer back to the rule.</h1><p>A useful freight calculation has three layers: the arithmetic, the service or tariff rule that chooses the inputs, and the operational limit that a calculator cannot approve.</p><h2>Production method</h2><ol><li>Start from one recurring shipping or packaging decision.</li><li>Prefer current carrier, standards-body, pallet-pool, or freight-provider sources.</li><li>Write the formula independently and expose every material assumption.</li><li>Test a worked example and common boundary cases.</li><li>Publish a review date and record material revisions.</li></ol><h2>Source review ledger</h2><div className="review-table"><div><span>Dimensional weight</span><strong>FedEx, UPS, DHL, USPS public guidance</strong><time>Reviewed August 6, 2026</time></div><div><span>Pallet loading</span><strong>EPAL and ISO pallet references</strong><time>Reviewed August 6, 2026</time></div><div><span>LCL weight or measure</span><strong>Maersk LCL terms and glossary</strong><time>Reviewed August 6, 2026</time></div></div><h2>Editorial independence</h2><p>Guide pages must solve distinct questions with distinct examples; they are not keyword-swapped copies. Partner links, if introduced, are separated from formulas and do not change calculator results.</p><h2>Privacy and analytics</h2><p>Inputs are processed locally in the browser. Analytics records page paths and high-level actions such as opening a tool, completing a calculation, or copying a result. It does not intentionally transmit calculator field values.</p><p><Link className="button button-primary" href="/resources">Download reference assets</Link></p></div><SiteFooter/></main>;
}
